# Python for Data Science
## Session 4 
### Basic Libraries I

---

## Outline

1. Numpy for numerical operations

2. Scipy for scientific computing

3. Math, os, glob, shutil 

---

## Basic Libraries I
 
Numpy provides a multidimensional array **object** and various methods for fast operations on arrays (arrays and matrices). These operations include mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In this session, we will learn some of the most common ones.



In [1]:
# To import a library we just need to use
import numpy as np

# TIP: Take a look at the references from the libraries you are using. Sometimes there are already-built methods that can save you lines and lines of code... Here the numpy as an example: https://numpy.org/doc/stable/reference/index.html

In [ ]:
# To create a simple array, we can use a list to instantiate an object
ar = np.array([-1, 2, 0, 6, 4])
ar 

In [ ]:
# Similar to list, we can access any of elements in the array
print(f"This is the last number of the array: {ar[-1]}") 

In [ ]:
# We can also slice them
print(f"These are the first three elements of the array: {ar[:3]}")

In [ ]:
# One thing, array can do, but list cannot is provide a subset of indices
print(f"This is a subarray formed by indices 2, 4 and 0: {ar[[2,4,0]]}")

In [ ]:
# If we try it with a list...
l = [-1, 2, 0, 6, 4]
print(f"This is a sublist formed by indices 2, 4 and 0: {l[[2,4,0]]}")

---

## Basic Libraries I

We can perform multiple mathematical operations over arrays. Some of them are similar to the built-in ones we have for lists.


In [ ]:
# let's create two vectors
u = np.array([1,2,3,4])
v = np.array([4,3,1,2])

In [ ]:
# Sum or substract two vectors element by element
u + v # equivalent to np.sum([u,v])

In [ ]:
u - v

In [ ]:
# multiplying or dividing them
u / v

In [ ]:
u * v

In [ ]:
# Power or sqrt
np.pow(u, 2) # equivalent to u ** 2

In [ ]:
np.sqrt(u)

In [ ]:
# dot product
np.dot(u, v) # equivalent to np.sum(u*v)

In [ ]:
# mean, median, std
np.mean(u)

In [ ]:
np.median(u)

## Basic Libraries I

Regarding changing ordering or sorting we have multiple options. 

In [ ]:
a = np.array([3, 0, 1, 4, 8])

In [ ]:
# We simply need to run
np.sort(a)

In [ ]:
# Same as the list, we can invert the original order by simply
a[::-1]

In [ ]:
# You can also select the type of algorithm to sort an array
np.sort(a, kind='quicksort') # mergesort, heapsort

In [ ]:
# Another interesting thing we can have with sort is to order based on different fields
values = [('Jaume', 2023, 9.4), ('James', 2021, 9.1), ('Marta', 2021, 8.3)]
dtype = [('name', 'S10'), ('year', int), ('grade', float)]

a = np.array(values, dtype=dtype)
a

In [ ]:
# Sorting by grade
np.sort(a, order='grade')

In [ ]:
# Sorting first by year, and when they have the same year, doing it by grade
np.sort(a, order=['year', 'grade'])

In [ ]:
np.sort(a, order=['year'])

In [ ]:
# the same way you sort, you can get the original indices sorted instead of the sorted array
a = np.array([3, 1, 6, 5])
np.argsort(a)

In [ ]:
# there is also a cool method called, unique, it gives you all the unique elements in a list/array
a = np.array([1, 1, 1, 2, 5, 6, 5, 9])
np.unique(a)

## Basic Libraries I

Selecting random elements from a list can be also performed from numpy.

In [ ]:
# Randomly create integer numbers ranging from 0 to 9
a = np.random.randint(0, 10)
a

In [ ]:
# Randomly creating an array of 10 floats from a normal distribution, mean 0 and std 1
a = np.random.randn(10)
a

In [ ]:
# Randomly selecting a value in a list/array (using uniform distribution)
np.random.choice(['a', 1, 'b', 0.4])

In [ ]:
# Randomly generating numbers using a uniform distribution over the interval [0, 1]
np.random.rand(10)

In [ ]:
# Create a random permutation from a list/array
np.random.permutation([23, 3, 2, -1])

In [ ]:
# Important, how to reproduce your results over and over
np.random.seed(123) # we can also pass a str, float that gets transformed into a fixed-size integer
np.random.choice([23, 3, 2, -1, 31, 6, -34, 0])

## Basic Libraries I

Other useful operations consist in modifying the shape and stack or concatenate elements.You can also created new arrays with buit-in methods such as **ones**, **zeros**, **ones_like**, **zeros_like**, and even define their type, **astype**.

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [3]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
c = np.stack([a,b])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.reshape(c, (1, 8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [6]:
c.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
c.swapaxes(0,1) # swapping the axes

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [8]:
c.transpose(1,0) # tranposing multiple axes at the same time

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
ones = np.ones(4) # you can also create given a size new arrays with
ones

In [ ]:
zeros = np.zeros_like(ones).astype('uint8') # you can do it with other types, e.g. float, uint16...
zeros

## Basic Libraries I

Logic operations are often used when handling arrays or matrices. These are some practical examples.

In [ ]:
# We can work with integers to create logical arrays
u = np.array([0, 1, 0, 1, 1]) # equivalent to u = [False, True, False, True , True]
v = np.array([1, 0, 0, 1, 0]) # you can also transform them to booleans np.bool(u)

In [ ]:
np.logical_and(u, v)

In [ ]:
np.logical_or(u, v)

In [ ]:
np.logical_not(u)

## Basic Libraries I

Numpy also provides methods to save and load numpy objects efficiently.

In [ ]:
a = np.array([0, 10, 14, 17, 19])

In [ ]:
np.save("session_4_array.npy", a)

In [ ]:
b = np.load("session_4_array.npy")
b

## Basic Libraries I

Scipy provides algorithms for statistics, optimization, integration, interpolation, algebraic equations, differential equations, and many other classes of problems. In this session, we will look at a few cases where they are normaly used. 

In [ ]:
# 1. Solving typical system of equations

import numpy as np
from scipy import linalg

# Coefficient matrix A and constants b
# 10x + y = 10
# 2x + 3y = 1

A = np.array([[10, 1], [2, 3]])
b = np.array([10, 1])


# Solve for x
x = linalg.solve(A, b)
print(x)

print(10*x[0] + 1*x[1])
print(2*x[0] + 3*x[1])

In [ ]:
# 2. Integrating a function over an interval 
from scipy import integrate

# Define a simple function to integrate
def f(x):
    return x**2 # x^2

# Integrate f(x) from 0 to 1
result, error = integrate.quad(f, 0, 2)
print(result)

In [ ]:
# 3. Integrating a function over an interval 
from scipy import optimize

# Define a quadratic function
def f(x):
    return x**2 + x + 1

# Find the minimum
result = optimize.minimize(f, x0=0)  # x0 is the initial guess
print(result.x)

In [ ]:
# 4. Interpolating between 2D points

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

# 4.1. Define some scattered 2D points (x, y) and corresponding z values
points = np.random.rand(10, 2) * 10  # 10 random points in 2D (x, y)
x = points[:, 0]  # Take the x-coordinates
z = np.sin(points[:, 0]) + np.cos(points[:, 1])  # z = sin(x) + cos(y) based on x and y

# 4.2 Sort x and z for proper interpolation (since x needs to be sorted)
sorted_indices = np.argsort(x)
x_sorted = x[sorted_indices]
z_sorted = z[sorted_indices]

# 4.3 Perform 1D interpolation along the x-axis
interp_func = interp1d(x_sorted, z_sorted, kind='cubic')  # Cubic interpolation

# 4.4. Create new x points for interpolation
x_new = np.linspace(min(x_sorted), max(x_sorted), 100)  # 100 new points along x-axis
z_new = interp_func(x_new)

# Step 5: Plot the original points and the 1D interpolation result
plt.figure(figsize=(8, 6))

# Plot original 2D points (x, z) as scatter plot
plt.scatter(x, z, color='red', label='Original Points')

# Plot the interpolated curve
plt.plot(x_new, z_new, label='Interpolated Curve', color='blue')

plt.title('1D Interpolation of 2D Points along X-Axis')
plt.xlabel('X')
plt.ylabel('Z (Interpolated)')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
# 5. Run a simple t-test over two distributions

from scipy import stats

# Two samples
sample1 = np.random.normal(loc=5, scale=1, size=100) # samples 100 points using a N(5, 1)
sample2 = np.random.normal(loc=5.5, scale=1, size=100) # samples 100 points using a N(5.5, 1)

# Perform t-test
_, p_value = stats.ttest_ind(sample1, sample2)
print(p_value)

# If the two populations come from the same distrubution the p-value should be high, typically above 0.05. 
# It the value is close to 1, the two samples are most probably coming from the same distribution.

## Basic Libraries I

Another library used when developing algorithms is Math. This is a **built-in** library in Python. It is worth mentioning that most of the mathematical functions and constants are covered by Scipy and Numpy. However, it is worth knowing it, since is a built-in library.

In [ ]:
import math

In [ ]:
# Square root, power, absolute value
math.sqrt(16)

In [ ]:
math.pow(2, 3)

In [ ]:
math.fabs(-10.5)

In [ ]:
# Calculate sinus, cosinus, tangent
angle = math.pi / 4  # in gradients
math.sin(angle) / math.cos(angle) == math.tan(angle)

In [ ]:
# Exponential, logarithm (ln), # Logarithm base 10
math.exp(1)

In [ ]:
math.log(10)

In [ ]:
math.log10(100)

In [ ]:
# Rounding down (floor) and up (ceil), and factorial
print(f"floor value for 2.8: {math.floor(2.8)} and ceil value for 2.1: {math.ceil(2.1)}")

In [ ]:
print(f"Factorial value of 4: {math.factorial(4)}")

## Basic Libraries I

When manipulating files and folder, you may want to use the following **built-in** libraries: os, glob and shutil. Let's staart with **os**.

In [2]:
import os

In [ ]:
# Let's check what files we have in a specific folder
os.listdir('session_4/')

In [ ]:
# Let's get the absolute path
os.getcwd()

In [ ]:
# Create a new folder
os.mkdir('new_folder')

In [ ]:
[file for file in os.listdir('.') if 'new_folder' in file]

In [ ]:
# Remove it now
os.rmdir('new_folder')

In [ ]:
[file for file in os.listdir('.') if 'new_folder' in file]

In [ ]:
# Check if a file exists
print(os.path.exists('session_4.ipynb'))

In [ ]:
# You can also join paths or get the file out of the full path
os.path.join('session_4/', 'annotations')

In [ ]:
os.path.basename('session_4/annotations/20240101_174301_SN33_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_404_3770.txt')

## Basic Libraries I

Let's keep working now with **glob**.

In [3]:
import glob

In [42]:
# Similar to os, you can also list files, but you can provide wildcards 
glob.glob('session_4/annotations/*.txt')

['session_4/annotations\\20240101_174301_SN33_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_404_3770.txt',
 'session_4/annotations\\20240101_174301_SN33_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_404_3772.txt',
 'session_4/annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_552_4162.txt',
 'session_4/annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_552_4164.txt',
 'session_4/annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_554_4162.txt',
 'session_4/annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_392_3740.txt',
 'session_4/annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_392_3742.txt',
 'session_4/annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_396_3752.txt',
 'session_4/annotations\\20240102_185527_SN27_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_740_3850.txt',
 'session_4/annotations\\20240102_185605_SN27_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_690_3572.txt',
 'session_4/annotati

In [43]:
# It does provide a great tool to list all the files within a folder, and also do it recursively
glob.glob('session_4/**/*.txt', recursive=True)

['session_4\\annotations\\20240101_174301_SN33_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_404_3770.txt',
 'session_4\\annotations\\20240101_174301_SN33_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_404_3772.txt',
 'session_4\\annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_552_4162.txt',
 'session_4\\annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_552_4164.txt',
 'session_4\\annotations\\20240101_192856_SN24_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-10N_554_4162.txt',
 'session_4\\annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_392_3740.txt',
 'session_4\\annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_392_3742.txt',
 'session_4\\annotations\\20240101_213601_SN31_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_396_3752.txt',
 'session_4\\annotations\\20240102_185527_SN27_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_740_3850.txt',
 'session_4\\annotations\\20240102_185605_SN27_QUICKVIEW_VISUAL_1_1_10_SATL-2KM-11N_690_3572.txt',
 'session_

## Basic Libraries I

Let's finally work with shutil. This library provides the usual bash commands you have in your terminal.

In [13]:
import shutil as sh

In [ ]:
# Copy a file into a new place
sh.copy('slides_install_guide.txt', 'session_4/')

In [ ]:
# instead of listing the current directory, os.listdir('.'), we can
ls session_4/

In [ ]:
# Move it now outside this folder
sh.move('session_4/slides_install_guide.txt', 'slides_install_guide_copy.txt')

In [ ]:
ls

In [ ]:
# let's create a folder to remove later
os.mkdir('folder_to_be_removed')

In [ ]:
# Remove a folder and its content
sh.rmtree('folder_to_be_removed/')

## Basic Libraries I

Let's jump into today's exercice.

### Exercise


Given a zip file with a subfolder with multiple annotations, where the name convention for each one of them is: 

{DATE}_{TIME}_SN{SATELLITE_NUMBER}_QUICKVIEW_VISUAL_{VERSION}_{UNIQUE_REGION}.txt

where:

- DATE expressed as YYYYMMDD (year, month and day), e.g. 20241201, 20230321 ...
- TIME expressed as HHMMSS (hour, minutes and seconds), e.g. 2134307
- SATELLITE_NUMBER an integer that represents the satellite number.
- VERSION provides the version of the pipeline, e.g. "0_1_2", "1_3_1" ...
- UNIQUE_REGION provides a unique location in the form of a string, e.g SATL-2KM-10N_552_4164

Find out the following thing about your data:

1. How many files the annotations folder has.
2. How many of them follow the name convention expressed above.
3. How many of annotations you have per month and year. Which month has more annotation files.
4. Create a new annotations folder with multiple folders corresponding to a month.
5. Print all the annotations from the most recent to the oldest one. 
6. How many different satellites there are, how many annotations we have per satellite number, and which one was used in the most recent annotation file. 
7. How many unique regions there are.

some tips:
- str class has a method called split, you can use it to get each field per annotation.
- you can use sort from numpy on strings.

In [ ]:
#number of files in the annotations folder
files=os.listdir('session_4/annotations')
number_of_files_annotations=len(files)
print(f'there are {number_of_files_annotations} files in the annotation folder')

#counting the number of files that follow the convension
files_following_convension=0
files_NOT_following_convension=0
for file in files:
    name=os.path.basename(file)
    date=name.split('_')[0]
    time=name.split('_')[1]
    satellite=name.split('_')[2]
    satellite_num=int(name.split('_')[2][2:])
    version=name.split('_')[5:8]
    unique_region=name.split('_')[8:]
    if (len(date) == 8 and 
        len(time) == 6 and
        satellite[0:2]=='SN' and 
        isinstance(satellite_num,int) and
        name.split('_')[3] == "QUICKVIEW" and 
        name.split('_')[4] == "VISUAL" and
        all(num.isdigit() for num in version) and
        unique_region[0][:4]=='SATL' and len(unique_region[1])==3 and len(unique_region[2])==8):  
        files_following_convension += 1
    else:
        files_NOT_following_convension += 1

print(f'{files_following_convension} files follow the name convension')
print(f'{files_NOT_following_convension} files do not follow the name convension')

#counting files based on month and year through the use of dictionaries
months={}
years={}
for file in files:
    year=file[:4]
    month=file[4:6]

    if year in years:
        years[year]+=1
    else:
        years[year]=1
    
    if month in months:
        months[month]+=1
    else:
        months[month]=1

max_month=max(months)
print(f'{max_month} is the month occuring the most')

#creating a new annotations folder with folders for each month
os.mkdir('session_4/new_annotations')
for month in months:
    os.mkdir(f'session_4/new_annotations/{month}')

#print all annotations from the most recent to the oldest one
reversed_files=files[::-1]
print(reversed_files)

#identifying how many satellites are there, how often each satellite is present in annotations and which satellite was used most recently
satellites={}
for file in files:
    name=os.path.basename(file)
    satellite_num=name.split('_')[2][2:]
    if satellite_num in satellites:
        satellites[satellite_num]+=1
    else:
        satellites[satellite_num]=1

print(f'there are {len(satellites)} different satellites')

for satellite in satellites.keys():
    print(f'the satellite number {satellite} is present in {satellites[satellite]} annotations')

most_recent=os.path.basename(files[-1]).split('_')[2][2:]

print(f'{most_recent} was the satellite used most recently')

#counting how many unique regions are there
region=list()
for file in files:
    name=os.path.basename(file)
    unique_region=name.split('_')[8:]
    region.append("_".join(unique_region))

#substituting the list with a set to ensure only unique values are kept
region=set(region)

print(f'there are {len(region)} unique regions')

there are 206 files in the annotation folder
194 files follow the name convension
12 files do not follow the name convension
06 is the month occuring the most
['20240623_215120_SN29_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-10N_596_4134.txt', '20240623_215102_SN43_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_384_3750.txt', '20240623_193704_SN27_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_566_3734.txt', '20240619_215556_SN29_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-10N_742_4460.txt', '20240619_185757_SN24_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_528_3700.txt', '20240619_052401_SN30_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-52N_368_4336.txt', '20240618_215539_SN31_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_458_3756.txt', '20240618_215539_SN31_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_452_3740.txt', '20240618_193146_SN27_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_530_3682.txt', '20240617_211350_SN29_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_724_3614.txt', '20240617_184443_SN24_QUICKVIEW_VISUAL_1_7_0_SATL-2KM-11N_702_3566.txt', '20240617_052859_SN29_QUICKVIEW_VISUA